#[cfg(feature = "mkl")]
extern crate intel_mkl_src;

#[cfg(feature = "accelerate")]
extern crate accelerate_src;

use clap::{Parser, ValueEnum};
use std::io::Write;
use tokenizers::Tokenizer;

use candle::Tensor;
use candle_transformers::generation::{LogitsProcessor, Sampling};

use candle_examples::token_output_stream::TokenOutputStream;

// Import your new quantized SmolLM3 implementation
use candle_transformers::models::smol::quantized_smollm3;
use candle_transformers::models::smol::quantized_smollm3::QuantizedModelForCausalLM;

const DEFAULT_PROMPT: &str = "Write a Rust function to calculate the factorial of a given number.";

#[derive(Clone, Debug, Copy, PartialEq, Eq, ValueEnum)]
enum Quantization {
    #[value(name = "q4_k_m")]
    Q4KM,
    #[value(name = "q8_0")]
    Q8_0,
    #[value(name = "f16")]
    F16,
}

impl Quantization {
    fn filename_unsloth(&self) -> &'static str {
        match self {
            Self::Q4KM => "SmolLM3-3B-Q4_K_M.gguf",
            Self::Q8_0 => "SmolLM3-3B-Q8_0.gguf",
            Self::F16 => "SmolLM3-3B-F16.gguf",
        }
    }

    fn filename_ggml(&self) -> &'static str {
        match self {
            Self::Q4KM => "SmolLM3-Q4_K_M.gguf",
            Self::Q8_0 => "SmolLM3-Q8_0.gguf",
            Self::F16 => "SmolLM3-f16.gguf",
        }
    }

    fn size_gb(&self) -> f32 {
        match self {
            Self::Q4KM => 1.92,
            Self::Q8_0 => 3.28,
            Self::F16 => 6.16,
        }
    }
}

#[derive(Clone, Debug, Copy, PartialEq, Eq, ValueEnum)]
enum Repo {
    #[value(name = "unsloth")]
    Unsloth,
    #[value(name = "ggml")]
    Ggml,
}

impl Repo {
    fn repo_id(&self) -> &'static str {
        match self {
            Self::Unsloth => "unsloth/SmolLM3-3B-GGUF",
            Self::Ggml => "ggml-org/SmolLM3-3B-GGUF",
        }
    }
}

#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// GGUF file to load, typically a .gguf file generated by quantization tools
    #[arg(long)]
    model: Option<String>,

    /// The initial prompt
    #[arg(long)]
    prompt: Option<String>,

    /// The length of the sample to generate (in tokens).
    #[arg(short = 'n', long, default_value_t = 1000)]
    sample_len: usize,

    /// The tokenizer config in json format.
    #[arg(long)]
    tokenizer: Option<String>,

    /// The temperature used to generate samples, use 0 for greedy sampling.
    #[arg(long, default_value_t = 0.8)]
    temperature: f64,

    /// Nucleus sampling probability cutoff.
    #[arg(long)]
    top_p: Option<f64>,

    /// Only sample among the top K samples.
    #[arg(long)]
    top_k: Option<usize>,

    /// The seed to use when generating random samples.
    #[arg(long, default_value_t = 299792458)]
    seed: u64,

    /// Enable tracing (generates a trace-timestamp.json file).
    #[arg(long)]
    tracing: bool,

    /// Process prompt elements separately.
    #[arg(long)]
    split_prompt: bool,

    /// Penalty to be applied for repeating tokens, 1. means no penalty.
    #[arg(long, default_value_t = 1.1)]
    repeat_penalty: f32,

    /// The context size to consider for the repeat penalty.
    #[arg(long, default_value_t = 64)]
    repeat_last_n: usize,

    /// Quantization level (trade-off between size and quality).
    /// Q8_0: 3.3GB, best quality | Q4_K_M: 1.9GB, good balance | F16: 6.2GB, full precision
    #[arg(long, default_value = "q8_0")]
    quantization: Quantization,

    /// GGUF repository to use (ggml-org is official, unsloth has more quants)
    #[arg(long, default_value = "unsloth")]
    repo: Repo,

    /// Skip chat template formatting (use raw prompt, like base model)
    #[arg(long)]
    no_chat_template: bool,
}

impl Args {
    fn tokenizer(&self) -> anyhow::Result<Tokenizer> {
        let tokenizer_path = match &self.tokenizer {
            Some(config) => std::path::PathBuf::from(config),
            None => {
                let api = hf_hub::api::sync::Api::new()?;
                let api = api.model("HuggingFaceTB/SmolLM3-3B".to_string());
                api.get("tokenizer.json")?
            }
        };
        Tokenizer::from_file(tokenizer_path).map_err(anyhow::Error::msg)
    }

    fn model(&self) -> anyhow::Result<std::path::PathBuf> {
        let model_path = match &self.model {
            Some(config) => std::path::PathBuf::from(config),
            None => {
                let filename = match self.repo {
                    Repo::Unsloth => self.quantization.filename_unsloth(),
                    Repo::Ggml => self.quantization.filename_ggml(),
                };
                let repo_id = self.repo.repo_id();
                let api = hf_hub::api::sync::Api::new()?;
                println!("Downloading {} from {} (~{:.2}GB)...",
                    filename, repo_id, self.quantization.size_gb());
                api.repo(hf_hub::Repo::with_revision(
                    repo_id.to_string(),
                    hf_hub::RepoType::Model,
                    "main".to_string(),
                ))
                .get(filename)?
            }
        };
        Ok(model_path)
    }
}

fn format_size(size_in_bytes: usize) -> String {
    if size_in_bytes < 1_000 {
        format!("{size_in_bytes}B")
    } else if size_in_bytes < 1_000_000 {
        format!("{:.2}KB", size_in_bytes as f64 / 1e3)
    } else if size_in_bytes < 1_000_000_000 {
        format!("{:.2}MB", size_in_bytes as f64 / 1e6)
    } else {
        format!("{:.2}GB", size_in_bytes as f64 / 1e9)
    }
}

fn main() -> anyhow::Result<()> {
    use tracing_chrome::ChromeLayerBuilder;
    use tracing_subscriber::prelude::*;

    let args = Args::parse();
    let _guard = if args.tracing {
        let (chrome_layer, guard) = ChromeLayerBuilder::new().build();
        tracing_subscriber::registry().with(chrome_layer).init();
        Some(guard)
    } else {
        None
    };

    println!(
        "avx: {}, neon: {}, simd128: {}, f16c: {}",
        candle::utils::with_avx(),
        candle::utils::with_neon(),
        candle::utils::with_simd128(),
        candle::utils::with_f16c()
    );
    println!(
        "repo: {}, quantization: {:?} (~{:.2}GB)",
        args.repo.repo_id(),
        args.quantization,
        args.quantization.size_gb()
    );
    println!(
        "temp: {:.2} repeat-penalty: {:.2} repeat-last-n: {}",
        args.temperature, args.repeat_penalty, args.repeat_last_n
    );

    let model_path = args.model()?;
    let start = std::time::Instant::now();
    let device = candle_examples::device(false)?;

    // Load model using your new implementation - much simpler!
    println!("Loading model from {:?}...", model_path);
    let mut model = QuantizedModelForCausalLM::from_gguf(&model_path, &device)?;

    println!(
        "Model loaded in {:.2}s",
        start.elapsed().as_secs_f32(),
    );
    println!("Model config:");
    println!("  Vocab size: {}", model.config().vocab_size);
    println!("  Hidden size: {}", model.config().hidden_size);
    println!("  Num layers: {}", model.config().num_hidden_layers);
    println!("  Num heads: {}", model.config().num_attention_heads);
    println!("  Num KV heads: {}", model.config().num_key_value_heads);
    println!("  Head dim: {}", model.config().head_dim());
    println!("  RoPE theta: {:.0}", model.config().rope_theta);

    let tokenizer = args.tokenizer()?;
    let mut tos = TokenOutputStream::new(tokenizer);
    let prompt_str = args
        .prompt
        .clone()
        .unwrap_or_else(|| DEFAULT_PROMPT.to_string());

    println!("Raw prompt: {}", &prompt_str);

    let prompt_str = if args.no_chat_template {
        // Use raw prompt without chat template
        prompt_str
    } else {
        // Apply SmolLM3 chat template
        format!(
            "<|im_start|>system\n\
## Metadata\n\
\n\
Knowledge Cutoff Date: June 2025\n\
Today Date: 05 November 2025\n\
Reasoning Mode: /think\n\
\n\
## Custom Instructions\n\
\n\
You are a helpful AI assistant named SmolLM, trained by Hugging Face.\n\
\n\
<|im_start|>user\n\
{}<|im_end|>\n\
<|im_start|>assistant\n\
<think>\n\
\n\
</think>\n",
            prompt_str
        )
    };

    // Encode without adding special tokens (they're already in the template)
    let tokens = tos
        .tokenizer()
        .encode(prompt_str, false)
        .map_err(anyhow::Error::msg)?;

    let tokens = tokens.get_ids();
    println!("Encoded {} tokens", tokens.len());

    let to_sample = args.sample_len.saturating_sub(1);
    let mut all_tokens = vec![];

    let mut logits_processor = {
        let temperature = args.temperature;
        let sampling = if temperature <= 0. {
            Sampling::ArgMax
        } else {
            match (args.top_k, args.top_p) {
                (None, None) => Sampling::All { temperature },
                (Some(k), None) => Sampling::TopK { k, temperature },
                (None, Some(p)) => Sampling::TopP { p, temperature },
                (Some(k), Some(p)) => Sampling::TopKThenTopP { k, p, temperature },
            }
        };
        LogitsProcessor::from_sampling(args.seed, sampling)
    };

    let start_prompt_processing = std::time::Instant::now();

    let mut next_token = if !args.split_prompt {
        // Process entire prompt at once (recommended)
        let input = Tensor::new(tokens, &device)?.unsqueeze(0)?;
        let logits = model.forward(&input, 0)?;
        let logits = logits.squeeze(0)?.squeeze(0)?;
        logits_processor.sample(&logits)?
    } else {
        // Process prompt token by token (slower, for debugging)
        let mut next_token = 0;
        for (pos, token) in tokens.iter().enumerate() {
            let input = Tensor::new(&[*token], &device)?.unsqueeze(0)?;
            let logits = model.forward(&input, pos)?;
            let logits = logits.squeeze(0)?.squeeze(0)?;
            next_token = logits_processor.sample(&logits)?
        }
        next_token
    };

    let prompt_dt = start_prompt_processing.elapsed();

    all_tokens.push(next_token);

    print!("Output: ");
    if let Some(t) = tos.next_token(next_token)? {
        print!("{t}");
        std::io::stdout().flush()?;
    }

    // Get EOS token - SmolLM3 uses <|im_end|> for chat format
    let eos_token = if let Some(eos_id) = tos.tokenizer().get_vocab(true).get("<|im_end|>") {
        *eos_id
    } else if let Some(eos_id) = tos.tokenizer().get_vocab(true).get("<|endoftext|>") {
        *eos_id
    } else {
        128012  // Default SmolLM3 EOS token (from GGUF metadata: tokenizer.ggml.eos_token_id)
    };

    let start_post_prompt = std::time::Instant::now();

    let mut sampled = 0;
    for index in 0..to_sample {
        let input = Tensor::new(&[next_token], &device)?.unsqueeze(0)?;
        let logits = model.forward(&input, tokens.len() + index)?;
        let logits = logits.squeeze(0)?.squeeze(0)?;

        let logits = if args.repeat_penalty == 1. {
            logits
        } else {
            let start_at = all_tokens.len().saturating_sub(args.repeat_last_n);
            candle_transformers::utils::apply_repeat_penalty(
                &logits,
                args.repeat_penalty,
                &all_tokens[start_at..],
            )?
        };

        next_token = logits_processor.sample(&logits)?;
        all_tokens.push(next_token);

        if let Some(t) = tos.next_token(next_token)? {
            print!("{t}");
            std::io::stdout().flush()?;
        }

        sampled += 1;
        if next_token == eos_token {
            break;
        };
    }

    if let Some(rest) = tos.decode_rest().map_err(candle::Error::msg)? {
        print!("{rest}");
    }

    std::io::stdout().flush()?;
    let dt = start_post_prompt.elapsed();
    println!(
        "\n\n{:4} prompt tokens processed: {:.2} token/s",
        tokens.len(),
        tokens.len() as f64 / prompt_dt.as_secs_f64(),
    );
    println!(
        "{sampled:4} tokens generated: {:.2} token/s",
        sampled as f64 / dt.as_secs_f64(),
    );

    Ok(())
}